# Generated by Django 3.2.8 on 2021-11-18 21:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20211117_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activate_key_expired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 18, 21, 25, 35, 700596, tzinfo=utc), null=True),
        ),
    ]
